apiVersion: v1
kind: Service
metadata:
  name: service-handson
  labels:
    team: int
spec:
  selector:
    team: int
  type: NodePort
  ports:
  - name: service-handson-ngx
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 32000
