apiVersion: v1
kind: Service
metadata:
  name: service-handson
  labels:
    team: int
spec:
  selector:
    team: int
  type: ClusterIP
  ports:
  - name: service-handson-ngx
    protocol: TCP
    port: 8080
    targetPort: 80
  - name: service-handson-ngx-2
    protocol: TCP
    port: 8081
    targetPort: 80
