apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app
  labels:
    app: sample-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-python-app
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
      - name: sample-python-app
        image: abhishekf5/python-sample-app-demo:v1
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: sample-python-app-service
spec:
  selector:
    app: sample-python-app
  type: NodePort
  ports:
  - name: sample-python-app-service
    protocol: TCP
    port: 8888
    targetPort: 8000
    nodePort: 31000